In [0]:
# AI-Powered Security Anomaly Detection on Azure
#
# Author: Pooja Borade
#
# Technologies:
# - Python
# - Databricks
# - Pandas
# - NumPy
# - Scikit-learn
# - Azure OpenAI
# - Power BI
#
# Objective:
# Detect unusual login events using Machine Learning
# (Isolation Forest) and explain suspicious events
# using Azure OpenAI.

print("AI Security Anomaly Detection Project Started")

AI Security Anomaly Detection Project Started

In [0]:
# Import Required Libraries


import pandas as pd
import numpy as np

from datetime import datetime, timedelta
from datetime import timedelta

print("Libraries imported successfully!")

Libraries imported successfully!

In [0]:
# Step 1: Define Users and Their Normal Login Locations


# Make random numbers repeatable
np.random.seed(42)

# Users in our organization
users = ["Alice", "Bob", "Charlie", "David", "Eva"]

# Normal country for each user
normal_country = {
    "Alice": "US",
    "Bob": "US",
    "Charlie": "UK",
    "David": "US",
    "Eva": "Canada"
}

# Azure resources users can access
resources = [
    "VM-1",
    "Storage-1",
    "SQL-DB-1",
    "KeyVault-1",
    "WebApp-1"
]

print("Users Loaded Successfully")
print(users)

Users Loaded Successfully
['Alice', 'Bob', 'Charlie', 'David', 'Eva']

In [0]:
# Step 2: Generate Normal Login Activity


rows = []

start_date = datetime(2026, 7, 1)

for i in range(500):

    # Random employee
    user = np.random.choice(users)

    # Business hours only (8 AM - 6 PM)
    hour = np.random.randint(8, 18)

    # Random day in July
    timestamp = start_date + timedelta(
        days=np.random.randint(0, 30),
        hours=hour,
        minutes=np.random.randint(0, 60)
    )

    rows.append({
        "User": user,
        "Timestamp": timestamp,
        "Country": normal_country[user],
        "Hour": hour,
        "Status": "Success",
        "Resource": np.random.choice(resources)
    })

print(f"Generated {len(rows)} normal login events")

Generated 500 normal login events

In [0]:
# Step 3: Create Pandas DataFrame


df = pd.DataFrame(rows)
original_df = df.copy()

print("Dataset Created Successfully!")
print("Number of Records:", len(df))

Dataset Created Successfully!
Number of Records: 520

In [0]:
# Step 4: Display First Five Records

df.head()

      User           Timestamp Country  Hour   Status   Resource
0    David 2026-07-29 15:20:00      US    15  Success  Storage-1
1  Charlie 2026-07-11 14:10:00      UK    14  Success   WebApp-1
2    David 2026-07-24 15:02:00      US    15  Success   WebApp-1
3      Bob 2026-07-12 15:29:00      US    15  Success  Storage-1
4    David 2026-07-01 12:11:00      US    12  Success  Storage-1

In [0]:
# Step 5: Understand the Dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   User       500 non-null    object
 1   Timestamp  500 non-null    datetime64[ns]
 2   Country    500 non-null    object
 3   Hour       500 non-null    int64
 4   Status     500 non-null    object
 5   Resource   500 non-null    object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 23.6+ KB

In [0]:
# Step 6: Summary Statistics

df.describe(include="all")

         User                   Timestamp  ...   Status   Resource
count     500                         500  ...      500        500
unique      5                         NaN  ...        1          5
top     David                         NaN  ...  Success  Storage-1
freq      115                         NaN  ...      500        116
mean      NaN  2026-07-16 05:32:02.400000  ...      NaN        NaN
min       NaN         2026-07-01 08:46:00  ...      NaN        NaN
25%       NaN         2026-07-08 11:53:45  ...      NaN        NaN
50%       NaN         2026-07-16 09:36:00  ...      NaN        NaN
75%       NaN         2026-07-24 10:15:15  ...      NaN        NaN
max       NaN         2026-07-30 17:49:00  ...      NaN        NaN
std       NaN                         NaN  ...      NaN        NaN

[11 rows x 6 columns]

In [0]:
# Step 7: Inject Suspicious Login Events

anomaly_countries = ["Russia", "China", "North Korea", "Iran"]

for i in range(20):

    user = np.random.choice(users)

    timestamp = start_date + timedelta(
        days=np.random.randint(0, 30),
        hours=np.random.randint(0, 5),      # Midnight to 4 AM
        minutes=np.random.randint(0, 60)
    )

    rows.append({
        "User": user,
        "Timestamp": timestamp,
        "Country": np.random.choice(anomaly_countries),
        "Hour": timestamp.hour,
        "Status": "Failed",
        "Resource": np.random.choice(resources)
    })

print("20 suspicious login events added.")

20 suspicious login events added.

In [0]:
# Step 8: Refresh DataFrame


df = pd.DataFrame(rows)

print("Dataset Updated Successfully")
print("Total Records:", len(df))

Dataset Updated Successfully
Total Records: 520

In [0]:
# Step 9: View Last Records


df.tail(20)

        User           Timestamp      Country  Hour  Status    Resource
500    Alice 2026-07-03 04:08:00         Iran     4  Failed    SQL-DB-1
501    David 2026-07-01 03:03:00  North Korea     3  Failed        VM-1
502      Eva 2026-07-07 03:51:00       Russia     3  Failed  KeyVault-1
503    David 2026-07-28 01:36:00         Iran     1  Failed    WebApp-1
504  Charlie 2026-07-07 02:27:00        China     2  Failed    WebApp-1
505      Eva 2026-07-22 04:54:00        China     4  Failed    SQL-DB-1
506      Eva 2026-07-22 04:09:00  North Korea     4  Failed   Storage-1
507      Eva 2026-07-01 04:20:00        China     4  Failed   Storage-1
508      Eva 2026-07-21 04:17:00       Russia     4  Failed    WebApp-1
509    David 2026-07-17 02:48:00         Iran     2  Failed    SQL-DB-1
510      Eva 2026-07-20 04:25:00        China     4  Failed  KeyVault-1
511      Bob 2026-07-20 03:17:00         Iran     3  Failed    SQL-DB-1
512    Alice 2026-07-29 03:28:00        China     3  Failed   Storage-1
513      Eva 2026-07-10 04:48:00       Russia     4  Failed        VM-1
514    Alice 2026-07-09 00:01:00         Iran     0  Failed    WebApp-1
515    Alice 2026-07-10 01:57:00         Iran     1  Failed  KeyVault-1
516      Eva 2026-07-28 02:54:00        China     2  Failed    SQL-DB-1
517    Alice 2026-07-15 00:59:00  North Korea     0  Failed    WebApp-1
518  Charlie 2026-07-05 03:00:00  North Korea     3  Failed    WebApp-1
519      Eva 2026-07-08 00:22:00  North Korea     0  Failed        VM-1

In [0]:
# Step 10: Convert Categorical Data to Numbers

from sklearn.preprocessing import LabelEncoder

# Create LabelEncoder object
encoder = LabelEncoder()

# Convert text columns into numeric values
df["User"] = encoder.fit_transform(df["User"])
df["Country"] = encoder.fit_transform(df["Country"])
df["Status"] = encoder.fit_transform(df["Status"])
df["Resource"] = encoder.fit_transform(df["Resource"])

print("Categorical columns encoded successfully!")

df.head()

Categorical columns encoded successfully!

   User           Timestamp  Country  Hour  Status  Resource
0     3 2026-07-29 15:20:00        6    15       1         2
1     2 2026-07-11 14:10:00        5    14       1         4
2     3 2026-07-24 15:02:00        6    15       1         4
3     1 2026-07-12 15:29:00        6    15       1         2
4     3 2026-07-01 12:11:00        6    12       1         2

In [0]:
# Step 11: Select Features


features = [
    "User",
    "Country",
    "Hour",
    "Status",
    "Resource"
]

X = df[features]

print("Feature Matrix Created")
print(X.head())

Feature Matrix Created
   User  Country  Hour  Status  Resource
0     3        6    15       1         2
1     2        5    14       1         4
2     3        6    15       1         4
3     1        6    15       1         2
4     3        6    12       1         2

In [0]:
# Step 12: Train Isolation Forest Model


from sklearn.ensemble import IsolationForest

# Create the model
model = IsolationForest(
    n_estimators=100,
    contamination=0.04,
    random_state=42
)

# Train the model
model.fit(X)

print("Isolation Forest model trained successfully!")

Isolation Forest model trained successfully!

In [0]:
# Step 13: Predict Anomalies


df["Prediction"] = model.predict(X)

print("Predictions completed!")

df.head()

Predictions completed!

   User           Timestamp  Country  Hour  Status  Resource  Prediction
0     3 2026-07-29 15:20:00        6    15       1         2           1
1     2 2026-07-11 14:10:00        5    14       1         4           1
2     3 2026-07-24 15:02:00        6    15       1         4           1
3     1 2026-07-12 15:29:00        6    15       1         2           1
4     3 2026-07-01 12:11:00        6    12       1         2           1

In [0]:
# Step 14: Count Normal vs Anomalies


print(df["Prediction"].value_counts())

Prediction
 1    499
-1     21
Name: count, dtype: int64

In [0]:
# Step 15: Display Suspicious Login Events


anomalies = df[df["Prediction"] == -1]

print("Number of anomalies detected:", len(anomalies))

anomalies.head(10)

Number of anomalies detected: 21

     User           Timestamp  Country  Hour  Status  Resource  Prediction
430     4 2026-07-12 08:57:00        0     8       1         4          -1
500     0 2026-07-03 04:08:00        2     4       0         1          -1
501     3 2026-07-01 03:03:00        3     3       0         3          -1
502     4 2026-07-07 03:51:00        4     3       0         0          -1
503     3 2026-07-28 01:36:00        2     1       0         4          -1
504     2 2026-07-07 02:27:00        1     2       0         4          -1
505     4 2026-07-22 04:54:00        1     4       0         1          -1
506     4 2026-07-22 04:09:00        3     4       0         2          -1
507     4 2026-07-01 04:20:00        1     4       0         2          -1
508     4 2026-07-21 04:17:00        4     4       0         4          -1

In [0]:
# Step 16: Calculate Anomaly Scores


df["AnomalyScore"] = model.decision_function(X)

df[["AnomalyScore", "Prediction"]].head()

   AnomalyScore  Prediction
0      0.149795           1
1      0.105478           1
2      0.114638           1
3      0.138900           1
4      0.155716           1

In [0]:
# Step 17: Sort by Most Suspicious Events


df.sort_values(
    by="AnomalyScore",
    ascending=True
).head(10)

     User           Timestamp  Country  ...  Resource  Prediction  AnomalyScore
514     0 2026-07-09 00:01:00        2  ...         4          -1     -0.132934
517     0 2026-07-15 00:59:00        3  ...         4          -1     -0.130381
504     2 2026-07-07 02:27:00        1  ...         4          -1     -0.127896
515     0 2026-07-10 01:57:00        2  ...         0          -1     -0.124406
512     0 2026-07-29 03:28:00        1  ...         2          -1     -0.122394
503     3 2026-07-28 01:36:00        2  ...         4          -1     -0.106359
519     4 2026-07-08 00:22:00        3  ...         3          -1     -0.102316
500     0 2026-07-03 04:08:00        2  ...         1          -1     -0.101707
518     2 2026-07-05 03:00:00        3  ...         4          -1     -0.100222
502     4 2026-07-07 03:51:00        4  ...         0          -1     -0.094924

[10 rows x 8 columns]

In [0]:
# Step 18: Create Human-Readable Dataset


# Create a fresh copy of the original login data
report_df = pd.DataFrame(rows)

# Copy ML results into the readable dataframe
report_df["Prediction"] = df["Prediction"]
report_df["AnomalyScore"] = df["AnomalyScore"]

print("Human-readable report created!")

report_df.head()

Human-readable report created!

      User           Timestamp Country  ...   Resource Prediction AnomalyScore
0    David 2026-07-29 15:20:00      US  ...  Storage-1          1     0.149795
1  Charlie 2026-07-11 14:10:00      UK  ...   WebApp-1          1     0.105478
2    David 2026-07-24 15:02:00      US  ...   WebApp-1          1     0.114638
3      Bob 2026-07-12 15:29:00      US  ...  Storage-1          1     0.138900
4    David 2026-07-01 12:11:00      US  ...  Storage-1          1     0.155716

[5 rows x 8 columns]

In [0]:
# Step 19: Display Human-Readable Anomalies


human_anomalies = report_df[report_df["Prediction"] == -1]

human_anomalies.sort_values(
    by="AnomalyScore",
    ascending=True
).head(10)

        User           Timestamp  ... Prediction  AnomalyScore
514    Alice 2026-07-09 00:01:00  ...         -1     -0.132934
517    Alice 2026-07-15 00:59:00  ...         -1     -0.130381
504  Charlie 2026-07-07 02:27:00  ...         -1     -0.127896
515    Alice 2026-07-10 01:57:00  ...         -1     -0.124406
512    Alice 2026-07-29 03:28:00  ...         -1     -0.122394
503    David 2026-07-28 01:36:00  ...         -1     -0.106359
519      Eva 2026-07-08 00:22:00  ...         -1     -0.102316
500    Alice 2026-07-03 04:08:00  ...         -1     -0.101707
518  Charlie 2026-07-05 03:00:00  ...         -1     -0.100222
502      Eva 2026-07-07 03:51:00  ...         -1     -0.094924

[10 rows x 8 columns]

In [0]:
# Step 20: Install Azure OpenAI SDK


%pip install openai

Requirement already satisfied: openai in /databricks/python3/lib/python3.12/site-packages (2.14.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /databricks/python3/lib/python3.12/site-packages (from openai) (4.7.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /databricks/python3/lib/python3.12/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /databricks/python3/lib/python3.12/site-packages (from openai) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /databricks/python3/lib/python3.12/site-packages (from openai) (2.10.6)
Requirement already satisfied: sniffio in /databricks/python3/lib/python3.12/site-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in /databricks/python3/lib/python3.12/site-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /databricks/python3/lib/python3.12/site-packages (from openai) (4.12.2)
Requirement already satisfied: idna>=2.8 in /databricks/python3/lib/python3.12/site-packages (from anyio<5,>=3.5.0->openai) (3.7)
Requirement already satisfied: certifi in /databricks/python3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /databricks/python3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /databricks/python3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /databricks/python3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /databricks/python3/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->openai) (2.27.2)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
# Step 21: Configure Azure OpenAI Client


from openai import AzureOpenAI

print("Azure OpenAI SDK Loaded Successfully!")

Azure OpenAI SDK Loaded Successfully!

In [0]:
# Step 22: Test Azure OpenAI Connection


from openai import AzureOpenAI

client = AzureOpenAI(
    api_key="YOUR_AZURE_OPENAI_API_KEY",
    api_version="2025-01-01-preview",
    azure_endpoint="https://poojaborade0707-9391-resource.services.ai.azure.com/"
)

deployment_name = "gpt-5-mini"

print("Connected!")

Connected!

In [0]:
# Step 23: Create AI Report Columns


report_df["AI_Explanation"] = ""
report_df["Severity"] = ""
report_df["Recommendation"] = ""
report_df["IncidentSummary"] = ""

print(report_df.columns)

Index(['User', 'Timestamp', 'Country', 'Hour', 'Status', 'Resource',
       'Prediction', 'AnomalyScore', 'AI_Explanation', 'Severity',
       'Recommendation', 'IncidentSummary'],
      dtype='object')

In [0]:
# Step 24: Select Top 5 Most Suspicious Anomalies

Sort anomalies by anomaly score (lowest = most suspicious)
top_anomalies = report_df[
    report_df["Prediction"] == -1
].sort_values(
    by="AnomalyScore",
    ascending=True
).head(5)

top_anomalies

        User           Timestamp  ... Recommendation  IncidentSummary
514    Alice 2026-07-09 00:01:00  ...
517    Alice 2026-07-15 00:59:00  ...
504  Charlie 2026-07-07 02:27:00  ...
515    Alice 2026-07-10 01:57:00  ...
512    Alice 2026-07-29 03:28:00  ...

[5 rows x 12 columns]

In [0]:
# Step 25: Generate and Save AI Security Analysis


for index, row in top_anomalies.iterrows():

    prompt = f"""
You are a cybersecurity analyst.

Analyze the following login event.

Provide your response in this exact format:

Explanation:
(2-3 sentences)

Severity:
(Low, Medium, High, or Critical)

Recommendation:
(3-5 bullet points)

Incident Summary:
(1 short paragraph)

Login Event

User: {row['User']}
Country: {row['Country']}
Hour: {row['Hour']}
Status: {row['Status']}
Resource: {row['Resource']}
"""

    response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    ai_response = response.choices[0].message.content

    print("=" * 80)
    print(f"Anomaly Index: {index}")
    print(ai_response)
    print("=" * 80)

================================================================================
Anomaly Index: 514
Explanation:
A failed login for Alice was observed from an IP geolocated to Iran at 00:00 targeting WebApp-1. While this single failed attempt has limited immediate impact, the unusual geography and timing are suspicious and could indicate reconnaissance or credential-stuffing activity.

Severity:
Medium

Recommendation:
- Review authentication logs (past 24–72 hours) for additional failed or successful attempts from the same IP, ASN, or geographic region and for other users hitting WebApp-1.
- Verify Alice’s normal login patterns (locations, devices) and contact her to confirm whether this was legitimate; if anomalous, require an immediate password reset and enforce MFA.
- Temporarily block or rate-limit the source IP/ASN and consider applying geoblocking or additional challenge requirements for traffic originating from high-risk countries.
- Enable/validate alerts for new-geo or out-of-hours successful logins and continue monitoring the account and WebApp-1 for any follow-on activity.

Incident Summary:
At 00:00 a failed login attempt to WebApp-1 was recorded for user Alice from Iran; although only one failure was observed, the foreign origin and off-hours timing raise suspicion. Investigate authentication logs and user behavior, apply temporary access controls if needed, enforce MFA/password reset if confirmed anomalous, and maintain heightened monitoring.
================================================================================
================================================================================
Anomaly Index: 517
Explanation:
The event is a failed login for user Alice originating from North Korea at 00:00, a high-risk and likely anomalous geolocation for most corporate users. While the attempt failed (no confirmed compromise), the origin and timing suggest reconnaissance or credential-stuffing and warrant investigation and monitoring.

Severity:
Medium

Recommendation:
- Verify the source IP(s) and timestamps, block the IP and associated ranges if malicious, and add them to firewall/IPS reputation lists as appropriate.
- Review authentication logs for additional failed or successful attempts for Alice and other accounts, and look for patterns consistent with credential stuffing or brute force.
- Ensure MFA is enforced for Alice and other privileged accounts; if multiple suspicious events are found, force a password reset and review session tokens.
- Implement geofencing or country-based access controls for WebApp-1 (deny or challenge logins from high-risk countries) and create alerts for logins from unexpected locations.

Incident Summary:
A single failed login to WebApp-1 by user Alice was observed from North Korea at 00:00. Although no credentials appear to have been compromised, the anomalous and high-risk origin suggests possible automated attacks or reconnaissance; further log review, temporary blocking, increased monitoring, and corrective access controls are recommended.
================================================================================
================================================================================
Anomaly Index: 504
Explanation:
The failed login for user Charlie originated from an IP geolocated to China at 02:00 targeting WebApp-1, which is unusual with respect to time and location for many environments. A single failed attempt is not definitive evidence of compromise but is suspicious and warrants rapid verification and log correlation to rule out reconnaissance or credential stuffing.

Severity:
Medium

Recommendation:
- Verify whether Charlie has legitimate reasons to access the application from China at that hour (travel, VPN, contractor activity); contact the user if needed.
- Correlate logs for the source IP/ASN: check for multiple failed attempts, successful logins, other users targeted, and any associated reconnaissance or malware indicators in the last 24–72 hours.
- If the access is unexpected or the IP is malicious, block or rate-limit the source, force a password reset for the account, and ensure MFA is enabled for Charlie.
- Increase monitoring and alerting on WebApp-1 for follow-up attempts and consider temporarily raising account lockout sensitivity until the activity is assessed.

Incident Summary:
At 02:00 a failed authentication to WebApp-1 was recorded for user Charlie from an IP located in China; while a single failure does not prove compromise, the unusual time and geography elevate risk and justify immediate verification, log correlation, and short-term containment measures if the activity is confirmed to be unauthorized.
================================================================================
================================================================================
Anomaly Index: 515
Explanation:
A single failed login to a sensitive resource (KeyVault-1) by user Alice from Iran at 01:00 is anomalous and could indicate reconnaissance, credential-stuffing, or a mistyped login from an unexpected location. Because the target is a secrets store, even failed attempts from an unusual geolocation should be investigated promptly to rule out targeted access attempts.

Severity:
Medium

Recommendation:
- Review authentication logs (time series) for Alice and KeyVault-1 for additional failed or successful attempts, and correlate source IPs and user-agent strings.
- Verify Alice’s usual login locations and contact her out-of-band to confirm whether the attempt was legitimate; if not, treat it as suspicious.
- Ensure MFA is enforced for KeyVault access and apply conditional access rules to block or require additional verification for high-risk geolocations (including Iran) or unknown devices.
- Temporarily block or rate-limit the offending IP and increase monitoring/alerts for further attempts against KeyVault-1 and other privileged resources.
- If further anomalies are observed (or if there is any successful access), force a password reset for Alice, revoke active sessions/keys, and rotate any secrets that might be at risk.

Incident Summary:
At 01:00, user Alice had a failed login attempt to KeyVault-1 originating from Iran. No successful access is recorded yet, but the combination of a sensitive target and an unexpected geolocation warrants investigation, tighter access controls, and heightened monitoring.
================================================================================
================================================================================
Anomaly Index: 512
Explanation:
A failed login attempt for user Alice to the sensitive resource Storage-1 originated from China at 03:00. The attempt is suspicious because of the unusual geolocation and off-hours timing for many users, though a single failure does not confirm a compromise.

Severity:
Medium

Recommendation:
- Verify with Alice whether she was traveling, using a VPN, or attempting access at that time; if not, treat the attempt as suspicious.
- Review authentication logs for related activity (additional failed/successful attempts, source IPs, user-agent, and lateral attempts against other accounts/resources).
- Ensure MFA is enforced for Alice and for access to Storage-1; if MFA is not in place, enable it immediately.
- If the source IP or pattern appears malicious, block or geofence the IP and consider a temporary account lock and password reset for Alice.

Incident Summary:
At 03:00 a failed authentication for Alice targeting Storage-1 was observed from China; no successful access was recorded. Given the sensitive target, the off-hour timing, and foreign geolocation, investigate user context and surrounding logs, confirm legitimacy with the user, and strengthen controls (MFA, monitoring, and potential account lock/reset) as needed.
================================================================================

In [0]:
# Step 26: Display Final AI Security Report


for index, row in top_anomalies.iterrows():

    prompt = f"""
You are a cybersecurity analyst.

Analyze the following login event.

Provide your response in this exact format:

Explanation:
(2-3 sentences)

Severity:
(Low, Medium, High, or Critical)

Recommendation:
(3-5 bullet points)

Incident Summary:
(1 short paragraph)

Login Event

User: {row['User']}
Country: {row['Country']}
Hour: {row['Hour']}
Status: {row['Status']}
Resource: {row['Resource']}
"""

    response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    ai_response = response.choices[0].message.content

    # Save the complete AI response
    report_df.loc[index, "AI_Explanation"] = ai_response

    print(f"Completed analysis for anomaly {index}")

Completed analysis for anomaly 514
Completed analysis for anomaly 517
Completed analysis for anomaly 504
Completed analysis for anomaly 515
Completed analysis for anomaly 512

In [0]:
# Step 27: Display Top 5 AI Investigation Results


report_df.loc[
    report_df["Prediction"] == -1,
    ["User", "Country", "AnomalyScore", "AI_Explanation"]
].head(5)

      User  ...                                     AI_Explanation
430    Eva  ...  Explanation:\nA single successful authenticati...
500  Alice  ...
501  David  ...
502    Eva  ...
503  David  ...

[5 rows x 4 columns]

In [0]:
# Project Summary

In this project we:

- Generated simulated Azure login events
- Injected suspicious login attempts
- Used Isolation Forest to detect anomalies
- Ranked suspicious events
- Used Azure OpenAI GPT-5 Mini to explain each anomaly
- Produced an AI-assisted security investigation report